services:
  site-mkdocs:
    build: sitemkdocs
    image: kebeyah/python-mkdocs:v.1.1
    container_name: mkdocs-site

    volumes:
      - ./sitemkdocs/site:/sitemkdocs/site

    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 512M

    networks:
       default:
          #l'adresse ip du containeur
         ipv4_address: 172.30.0.11
       site-proxy:
         ipv4_address: 172.29.0.4

networks:
  default:
    name: rx_mkdocs
    driver: bridge
    external: false
    ipam:
      config:
        - subnet: 172.30.0.0/16
          gateway: 172.30.0.1

# LE RESEAU DU PROXY
  site-proxy:
    external: true
