# pour le serveur python
FROM  mysql:latest

LABEL description="Liste des membres du groupe 1"
LABEL author.name1="Ibrahima Sory FOFANA"
LABEL author.name2="Aissatou Djibril DIALLO"
LABEL author.name3="Aboubacar KANTE"
LABEL author.name4="Mathieu BEAVOGUI"

