FROM wordpress:php8.3-apache

# L'AUTEUR DE L'IMAGE 
LABEL description="C'est une image customiser de Wordpress phpmyadmin et de mysqlserver"

LABEL description="Liste des membres du groupe 1"
LABEL author.name1="Ibrahima Sory FOFANA"
LABEL author.name2="Aissatou Djibril DIALLO"
LABEL author.name3="Aboubacar KANTE"
LABEL author.name4="Mathieu BEAVOGUI"

